name: docs

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - main
jobs:
  docs:
    name: build rustdocs and put them on github pages
    runs-on: ubuntu-latest
    steps:
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@master
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy
        override: true
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.2.1
    - name: Build Documentation
      run: cargo +nightly doc
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        # Upload entire repository
        path: ./target/doc
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1

    # - name: Deploy Docs
    #   uses: peaceiris/actions-gh-pages@364c31d33bb99327c77b3a5438a83a357a6729ad
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_branch: rustdocs
    #     publish_dir: ./target/doc
    #     force_orphan: true
