name: docs

on:
  push:
    branches:
      - main
jobs:
  docs:
    name: build rustdocs and put them on github pages
    runs-on: ubuntu-latest
    steps:
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@master
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy
        override: true
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.2.1
    - name: Build Documentation
      run: cargo +nightly doc --no-deps --all
    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@bd8c6b06eba6b3d25d72b7a1767993c0aeee42e7
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: rustdocs
        publish_dir: ./target/doc
        force_orphan: true
